// Package preprocess wraps Run-ZimmermanTools.ps1 in a safely-callable
// Go API. It owns the embedded PS1 script, discovers a PowerShell
// interpreter at runtime, and runs the script as a subprocess with
// arguments built from a typed config struct (never from concatenated
// strings).
//
// The package is intentionally small in surface area. There are two
// public types -- Config (what the analyst wants run) and Runner
// (how it gets run) -- and one public method (Runner.Run). Everything
// else is internal.
//
// Security boundary:
//
//   - The embedded PS1 is read-only and content-verified at build time
//     via Go's embed. Nothing in the running binary can swap it out.
//
//   - Argv is built from typed fields with strict validation. Untrusted
//     strings (Operator, CollectionMethod) flow through os/exec's
//     argv-array path with no shell, so even pathological values like
//     `"; rm -rf /` are passed verbatim to PowerShell as a single
//     argument rather than being reinterpreted as shell syntax.
//
//   - Paths (ImagePath, OutputRoot) are validated as existing
//     directories before invocation, blocking misuse like `;` or `&&`
//     in path-shaped fields.
//
//   - The PS1 file path passed to PowerShell is generated by Go from
//     the temp directory; it is never analyst-supplied.
package preprocess

import (
	"bufio"
	"context"
	_ "embed"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"sync"
)

// scriptBytes is the verbatim content of Run-ZimmermanTools.ps1 as
// shipped with this build of Douglas. Extracting it to a temp file
// at runtime avoids the analyst's PATH or working directory affecting
// which script gets run. Building from the repo always produces the
// same bytes; modifying the file requires a rebuild.
//
//go:embed Run-ZimmermanTools.ps1
var scriptBytes []byte

// ScriptBytes returns a copy of the embedded preprocessor script. The
// /api/preprocess/script endpoint exposes this so analysts can verify
// the version Douglas would actually invoke against the standalone
// copy they may also have on disk.
func ScriptBytes() []byte {
	out := make([]byte, len(scriptBytes))
	copy(out, scriptBytes)
	return out
}

// ToolFilter lists the valid -ToolFilter values the PS1 accepts.
// Mirrors the PS1's own ValidateSet so both sides agree on what's
// supported. Surfaced via /api/preprocess/tools for the UI's checkbox
// list.
//
// Keep ordering: the UI renders checkboxes in this order, and the
// order is roughly "most useful first" so analysts pressed for time
// can grab the top of the list.
var ToolFilter = []ToolOption{
	{ID: "mft", Label: "MFT", Tool: "MFTECmd"},
	{ID: "evtx", Label: "Event Logs", Tool: "EvtxECmd"},
	{ID: "prefetch", Label: "Prefetch", Tool: "PECmd"},
	{ID: "amcache", Label: "Amcache", Tool: "AmcacheParser"},
	{ID: "shimcache", Label: "Shimcache", Tool: "AppCompatCacheParser"},
	{ID: "lnk", Label: "LNK Files", Tool: "LECmd"},
	{ID: "jumplist", Label: "Jump Lists", Tool: "JLECmd"},
	{ID: "shellbags", Label: "Shellbags", Tool: "SBECmd"},
	{ID: "srum", Label: "SRUM", Tool: "SrumECmd"},
	{ID: "sum", Label: "SUM (server)", Tool: "SumECmd"},
	{ID: "recmd", Label: "Registry (RECmd)", Tool: "RECmd"},
	{ID: "recyclebin", Label: "Recycle Bin", Tool: "RBCmd"},
}

// ToolOption is one row in the UI's checkbox list.
type ToolOption struct {
	ID    string `json:"id"`    // PS1 -ToolFilter value
	Label string `json:"label"` // UI display string
	Tool  string `json:"tool"`  // EZ Tool exe name (informational)
}

// IsValidToolID reports whether s matches one of the registered tool
// IDs. Used for input validation on the /api/preprocess endpoint.
func IsValidToolID(s string) bool {
	for _, t := range ToolFilter {
		if t.ID == s {
			return true
		}
	}
	return false
}

// Config is the typed-input shape of a preprocessor invocation.
// The wizard JSON-decodes the analyst's selections into one of these
// before passing it to Runner.Run; the runner builds the argv from
// these fields and never from a free-form string.
//
// All fields here mirror Run-ZimmermanTools.ps1 parameters. Adding a
// new flag means adding it here, in the script, and in the validator
// below -- there's no way to inject extra flags from the UI without
// passing through this struct.
type Config struct {
	ImagePath        string   `json:"imagePath"`
	OutputRoot       string   `json:"outputRoot"`
	HostName         string   `json:"hostName,omitempty"`
	CaseID           string   `json:"caseId,omitempty"`
	ToolsRoot        string   `json:"toolsRoot,omitempty"`
	ToolFilter       []string `json:"toolFilter,omitempty"`
	Operator         string   `json:"operator,omitempty"`
	CollectionMethod string   `json:"collectionMethod,omitempty"`
	RunHayabusa      bool     `json:"runHayabusa,omitempty"`
	RunBitsParser    bool     `json:"runBitsParser,omitempty"`
}

// Validate returns nil if cfg is safe to run, or an error describing
// the first invalid field. Validation is strict; we'd rather fail at
// /api/preprocess with a 400 than push a malformed value into argv.
func (c Config) Validate() error {
	if c.ImagePath == "" {
		return errors.New("imagePath is required")
	}
	if c.OutputRoot == "" {
		return errors.New("outputRoot is required")
	}
	if st, err := os.Stat(c.ImagePath); err != nil {
		return fmt.Errorf("imagePath: %w", err)
	} else if !st.IsDir() {
		return errors.New("imagePath is not a directory")
	}

	// OutputRoot rules: it doesn't have to exist (the PS1 uses
	// New-Item -Force to create the case folder + intermediates),
	// but the path has to be plausibly creatable. Specifically:
	//
	//   - If the path already exists, it must be a directory (not a
	//     file). Pointing OutputRoot at a file would silently break
	//     the script's later New-Item calls.
	//
	//   - If it doesn't exist, walk up to find the nearest existing
	//     ancestor. That ancestor must be a directory, which gives us
	//     a useful sanity check (catches typos like "C:\nope\x\y\z"
	//     where nothing on the chain exists) without forcing the
	//     analyst to pre-create the case folder.
	//
	// We don't try to create anything here — the validator is
	// side-effect-free. The work function does an explicit MkdirAll
	// right before invoking PowerShell so a cancelled wizard doesn't
	// leave behind stray empty directories.
	if err := validateCreatablePath(c.OutputRoot); err != nil {
		return fmt.Errorf("outputRoot: %w", err)
	}
	// HostName and CaseID are passed to PowerShell as literal arguments.
	// PowerShell will accept anything, but we restrict to a sane charset
	// so a careless analyst doesn't end up with path-fragment characters
	// in their case ID.
	if c.HostName != "" && !safeID.MatchString(c.HostName) {
		return errors.New("hostName may only contain letters, digits, dot, dash, underscore")
	}
	if c.CaseID != "" && !safeID.MatchString(c.CaseID) {
		return errors.New("caseId may only contain letters, digits, dot, dash, underscore")
	}
	// ToolsRoot if provided must be a directory.
	if c.ToolsRoot != "" {
		if st, err := os.Stat(c.ToolsRoot); err != nil {
			return fmt.Errorf("toolsRoot: %w", err)
		} else if !st.IsDir() {
			return errors.New("toolsRoot is not a directory")
		}
	}
	// ToolFilter entries must be in the canonical list.
	for _, t := range c.ToolFilter {
		if !IsValidToolID(t) {
			return fmt.Errorf("unknown tool id: %q (see /api/preprocess/tools)", t)
		}
	}
	// Operator and CollectionMethod are free-form strings shoved into
	// host.json's triage block. PowerShell handles the quoting since we
	// pass them as argv elements; the only restriction we impose is no
	// embedded NUL (defensive).
	if strings.ContainsRune(c.Operator, '\x00') {
		return errors.New("operator must not contain NUL")
	}
	if strings.ContainsRune(c.CollectionMethod, '\x00') {
		return errors.New("collectionMethod must not contain NUL")
	}
	return nil
}

// safeID is the validation regex for hostName/caseId. Tighter than the
// upload-filename sanitizer because these flow into directory names on
// disk and would be a nuisance with spaces.
var safeID = regexp.MustCompile(`^[A-Za-z0-9._-]+$`)

// validateCreatablePath returns nil if `p` either:
//
//   - already exists as a directory, or
//   - doesn't exist, but the nearest existing ancestor is a directory
//
// The "nearest existing ancestor" walk handles cases like
// "C:\Cases\acme-2026-05" where neither "C:\Cases" nor the case dir
// itself exists; as long as "C:\" exists and is a directory, we accept.
// PowerShell's New-Item -Force will recursively create the missing
// intermediates when the script runs.
//
// Returns an error for:
//   - relative paths (they'd resolve against Douglas's CWD, which is
//     usually NOT what the analyst meant; better to fail loudly)
//   - existing path that's a file (would break the script's later
//     mkdir attempts)
//   - path where no ancestor exists (e.g. "Q:\nothing" on a system
//     with no Q: volume mounted)
//   - filepath.Abs failure (malformed path)
//
// Has no filesystem side effects -- nothing is created here. The
// actual mkdir happens in the work function once the analyst has
// committed to the run.
func validateCreatablePath(p string) error {
	if !filepath.IsAbs(p) {
		return errors.New("must be an absolute path (e.g. C:\\Cases\\... or /opt/cases/...)")
	}
	abs, err := filepath.Abs(p)
	if err != nil {
		return fmt.Errorf("resolve path: %w", err)
	}
	// Walk up the path looking for an existing ancestor.
	cur := abs
	for {
		st, err := os.Stat(cur)
		if err == nil {
			// Found an existing entry. Must be a directory.
			if !st.IsDir() {
				if cur == abs {
					return errors.New("path exists but is not a directory")
				}
				return fmt.Errorf("ancestor %q exists but is not a directory", cur)
			}
			return nil
		}
		// Step up to the parent. filepath.Dir is documented to return
		// the path unchanged at the root, so we detect that and stop.
		parent := filepath.Dir(cur)
		if parent == cur {
			return fmt.Errorf("no existing ancestor of %q (path root not reachable)", abs)
		}
		cur = parent
	}
}

// Runner owns the PowerShell discovery + temp-extracted script. One
// Runner is shared across the process; New() panics if no PowerShell
// is found, callers should check Available() first via the discovery
// helpers.
type Runner struct {
	psPath     string // resolved powershell.exe / pwsh.exe path
	scriptPath string // extracted script location (under os.TempDir())

	mu     sync.Mutex // guards scriptPath cleanup
	closed bool
}

// New constructs a Runner. Returns (nil, error) if no PowerShell
// interpreter can be located. Callers running on non-Windows hosts
// will get an error here, which is the right behavior -- the script
// uses Windows-specific cmdlets (reg.exe, Get-ItemProperty against
// HKLM:, etc.) and cannot run on Linux/macOS.
func New() (*Runner, error) {
	psPath, err := discoverPowerShell()
	if err != nil {
		return nil, err
	}
	// Extract the embedded script to a temp file. Path constructed by
	// Go (not by any user input), so it's safe.
	tmp, err := os.CreateTemp("", "douglas-preproc-*.ps1")
	if err != nil {
		return nil, fmt.Errorf("write script: %w", err)
	}
	if _, err := tmp.Write(scriptBytes); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmp.Name())
		return nil, fmt.Errorf("write script: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmp.Name())
		return nil, fmt.Errorf("close script: %w", err)
	}
	return &Runner{psPath: psPath, scriptPath: tmp.Name()}, nil
}

// Close removes the temp script file. Idempotent.
func (r *Runner) Close() error {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.closed {
		return nil
	}
	r.closed = true
	if r.scriptPath != "" {
		return os.Remove(r.scriptPath)
	}
	return nil
}

// PSPath returns the resolved PowerShell interpreter path. Surfaced
// to the UI so the analyst can see what's actually getting invoked.
func (r *Runner) PSPath() string { return r.psPath }

// ScriptPath returns the on-disk path of the extracted script. The
// path lives under os.TempDir(); analysts curious about what they're
// running can read it.
func (r *Runner) ScriptPath() string { return r.scriptPath }

// Run invokes the preprocessor with the given config. Output (combined
// stdout+stderr) is streamed to onLine as each line arrives; the
// caller is expected to forward those into a jobs.Job's progress
// field. Returns the exit code and any error from invocation.
//
// Cancellation: when ctx is cancelled, the subprocess is killed. The
// caller should propagate ctx from the job's worker context so DELETE
// /api/jobs/{id} stops in-flight preprocessing.
func (r *Runner) Run(ctx context.Context, cfg Config, onLine func(line string)) (int, error) {
	if err := cfg.Validate(); err != nil {
		return -1, err
	}
	args := r.buildArgs(cfg)

	cmd := exec.CommandContext(ctx, r.psPath, args...)
	// Capture both streams together. PowerShell sends errors to stderr
	// in some paths but to the success stream via Write-Host in others;
	// merging gives the analyst one coherent log to read.
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return -1, fmt.Errorf("stdout pipe: %w", err)
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return -1, fmt.Errorf("stderr pipe: %w", err)
	}

	if err := cmd.Start(); err != nil {
		return -1, fmt.Errorf("start: %w", err)
	}

	// Two readers, one per stream. WaitGroup so we don't return before
	// both have drained -- the subprocess may be done but pipes can
	// still have buffered content.
	var wg sync.WaitGroup
	wg.Add(2)
	go streamLines(stdout, onLine, &wg)
	go streamLines(stderr, onLine, &wg)

	waitErr := cmd.Wait()
	wg.Wait()

	if waitErr != nil {
		// Non-zero exit returns *exec.ExitError. Other errors (e.g.
		// process killed via context) come back as their own types.
		var ee *exec.ExitError
		if errors.As(waitErr, &ee) {
			return ee.ExitCode(), nil
		}
		return -1, fmt.Errorf("wait: %w", waitErr)
	}
	return 0, nil
}

// buildArgs constructs the argv that will be passed to PowerShell.
// Every arg is a separate element in the slice -- no shell parsing,
// so embedded quotes/spaces in user-supplied fields can't escape into
// adjacent flags.
//
// The script is invoked via -File, which executes a script with the
// PowerShell-native parameter binding. -ExecutionPolicy Bypass is
// included so analysts whose corporate group policy restricts script
// execution can still run the preprocessor; this only affects the
// child process, not the analyst's session.
func (r *Runner) buildArgs(cfg Config) []string {
	args := []string{
		"-NoProfile",
		"-NonInteractive",
		"-ExecutionPolicy", "Bypass",
		"-File", r.scriptPath,
		"-ImagePath", cfg.ImagePath,
		"-OutputRoot", cfg.OutputRoot,
	}
	if cfg.HostName != "" {
		args = append(args, "-HostName", cfg.HostName)
	}
	if cfg.CaseID != "" {
		args = append(args, "-CaseId", cfg.CaseID)
	}
	if cfg.ToolsRoot != "" {
		args = append(args, "-ToolsRoot", cfg.ToolsRoot)
	}
	if len(cfg.ToolFilter) > 0 {
		// PowerShell accepts comma-separated values for string[]
		// parameters when passed via -File invocation. Each ID was
		// validated above against the canonical list.
		args = append(args, "-ToolFilter", strings.Join(cfg.ToolFilter, ","))
	}
	if cfg.Operator != "" {
		args = append(args, "-Operator", cfg.Operator)
	}
	if cfg.CollectionMethod != "" {
		args = append(args, "-CollectionMethod", cfg.CollectionMethod)
	}
	if cfg.RunHayabusa {
		args = append(args, "-RunHayabusa")
	}
	if cfg.RunBitsParser {
		args = append(args, "-RunBitsParser")
	}
	return args
}

// discoverPowerShell looks for a PowerShell interpreter. Prefers
// PowerShell 7+ (pwsh.exe) since it has fewer surprises in
// non-interactive use, but falls back to built-in Windows PowerShell
// (powershell.exe / powershell on non-Windows -- though the script
// itself requires Windows so non-Windows discovery is academic).
func discoverPowerShell() (string, error) {
	candidates := []string{"pwsh", "pwsh.exe", "powershell", "powershell.exe"}
	if runtime.GOOS != "windows" {
		// Strip the .exe candidates on Unix-like systems for clarity
		// in logs, even though LookPath handles either.
		candidates = []string{"pwsh", "powershell"}
	}
	for _, c := range candidates {
		if p, err := exec.LookPath(c); err == nil {
			return p, nil
		}
	}
	return "", errors.New("no PowerShell interpreter found in PATH (looked for pwsh, powershell)")
}

// streamLines reads r line-by-line, calling onLine for each line.
// Continues until EOF or error. Errors are swallowed -- the caller
// will see them as the subprocess's exit status. The bufio scanner
// uses a generous buffer so long PS-generated lines (e.g. transcript
// command echoes with full argument lists) don't get truncated.
func streamLines(rdr io.Reader, onLine func(string), wg *sync.WaitGroup) {
	defer wg.Done()
	scanner := bufio.NewScanner(rdr)
	// 1 MB max line length. PS lines are usually under a few hundred
	// bytes; allow much more so we never silently drop a long one.
	buf := make([]byte, 0, 64*1024)
	scanner.Buffer(buf, 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if onLine != nil {
			onLine(line)
		}
	}
	// scanner.Err() intentionally ignored; upstream knows the process
	// has terminated and can decide what to do with the exit code.
}
